config/routes.rb
Rails.application.routes.draw do

  root 'tops#top' # topページ

  resources :tops do
    collection do
      get :kiyac
      get :policy
      get :guide
    end
  end

  get 'login' => 'user_sessions#new', :as => :login # gem sorceryより。
  post 'login' => 'user_sessions#create' # gem sorceryのより。
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users, only: %i(new create show) do
    collection do
      get :usercat
    end
  end
  resource :profile, only: %i(show edit update destroy) do
    collection do
      get :delete_confirmation
    end
  end
  resources :cat_breeds, only: %i(index)
  resources :cats, only: %i(index new create update destroy)
  resources :password_resets, only: %i[new create edit update] # パスワードリセット用

  resources :posts, only: %i(index new show edit create update destroy) do
    resources :comments, only: %i[create update destroy], shallow: true
  end
  resources :likes, only: %i(create destroy)
  resources :post_by_cats, only: %i(index)
  resources :samebreedcats, only: %i(index)
  resources :like_lists, only: %i(index)
  resources :autocompletes, only: %i(index)

  resources :maps, only: %i(index show) do # GoogleマップAPIの導入により追加
    collection do
      get :search
    end
  end

  get 'line_events/show', to: 'line_events#show'
  post '/line_events', to: 'line_events#receive'
  put '/line_events', to: 'line_events#update'

  namespace :admin do
    root to: 'users#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i(index show edit update destroy)
    resources :posts, only: %i(index show edit update destroy)
    resources :cats, only: %i(index show edit update destroy)
    resources :tags, only: %i(index show edit update destroy)
    resources :comments, only: %i(index show edit update destroy)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, length: { maximum: 500 }

  def self.ransackable_attributes(auth_object = nil)
    %w[body]  # 検索時に猫の名前を検索できる
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::BaseController
  def index
    @q = Comment.ransack(params[:q])
    @comments = @q.result(distinct: true).order(created_at: :desc)
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      flash[:success] = t('admin.messages.update')
      redirect_to admin_comment_path(@comment)
    else
      flash.now[:danger] = t('admin.messages.update_faild')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy!
    flash[:success] = t('admin.messages.delete')
    redirect_to admin_comments_path
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  require 'line/bot'

  def client
    @client ||= Line::Bot::Client.new { |config|
      config.channel_secret = ENV['LINE_CHANNEL_SECRET']
      config.channel_token = ENV['LINE_CHANNEL_TOKEN']
    }
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    return if @comment.post.user.line_id.blank?

    client.push_message(@comment.post.user.line_id, { type: 'text', text: "#{@comment.post.user.name}さんの投稿、#{@comment.post.title}にコメントが追加されました!" })
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/views/admin/comments/_comment.html.erb
<div class="bg-white rounded-md shadow-md p-6 mb-6">
    <h2 class="text-xl font-semibold mb-2">コメントした投稿のタイトル</h2>
    <h2 class="text-lg font-semibold mb-4"><%= comment.post.title %></h2>

    <h2 class="text-xl font-semibold mb-2">コメント内容</h2>
    <h3 class="text-md font-semibold mb-4"><%= comment.body.truncate(10) %></h3>

    <h2 class="text-xl font-semibold mb-2">コメントしたユーザーの名前</h2>
    <h3 class="text-md font-semibold mb-4"><%= comment.user.name %></h3>

    <div class="flex space-x-2">
    <%= link_to '詳細', admin_comment_path(comment), class: 'text-blue-500 hover:underline', id: "admin-comment-show-id-#{comment.id}" %>
    <%= link_to '編集', edit_admin_comment_path(comment), class: 'text-green-500 hover:underline', id: "admin-comment-edit-id-#{comment.id}" %>
    <%= link_to '削除', admin_comment_path(comment), 
                class: 'text-red-500 hover:underline',
                data: { turbo_method: :delete, turbo_confirm: "コメントを削除しますか？" }, id: "admin-comment-delete-id-#{comment.id}" %>
    </div>
  </div>

app/views/admin/comments/_search.html.erb
<%= search_form_for @q, url: url do |f| %>
  <%= f.search_field :body_cont, class: 'form-control text-black px-1', placeholder: 'コメント検索' %>
  <%= f.submit '検索', class: 'btn btn-primary' %>
<% end %>

app/views/admin/comments/edit.html.erb
<div class="container mx-auto mt-8 text-black">
    <h1 class="text-3xl font-semibold mb-6 text-white">コメント編集画面</h1>
  
    <div class="bg-white rounded-md shadow-md p-6 mb-6">
      <%= form_with(model: @comment, url: admin_comment_path(@comment)) do |f| %>
        <div class="mb-4">
          <%= f.label :body, class: "block text-gray-700 text-sm font-bold mb-2" %>
           <%= f.text_area :body, class: "form-input w-full h-32 p-2 border rounded-md focus:outline-none focus:shadow-outline" %>

        </div>
  
        <div class="mb-4">
          <%= f.submit "コメント更新", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/admin/comments/index.html.erb
<div class="container mx-auto mt-8 text-black">
    <h1 class="text-3xl font-semibold mb-6 text-white p-2">コメント一覧</h1>

<div class="mb-4 p-4">
<%= render 'search', q: @q, url: admin_comments_path %>
</div>
  <%=render @comments %>
</div>

app/views/admin/comments/show.html.erb
<div class="container mx-auto mt-8 text-black">
    <h1 class="text-3xl font-semibold mb-6 text-white">コメント詳細</h1>
  
    <div class="bg-white rounded-md shadow-md p-6 mb-6">
      <h2 class="text-xl font-semibold mb-2">コメントしたユーザー</h2>
      <h3 class="text-md font-semibold mb-4"><%= link_to @comment.user.name, admin_user_path(@comment.user), class: 'text-blue-500 hover:underline' %></h3>
  
      <h2 class="text-xl font-semibold mb-2">コメントした投稿のタイトル</h2>
      <h3 class="text-md font-semibold mb-4"><%= link_to @comment.post.title, admin_post_path(@comment.post), class: 'text-blue-500 hover:underline' %></h3>
  
      <h2 class="text-xl font-semibold mb-2">コメント内容</h2>
      <h3 class="text-md font-semibold mb-4"><%= @comment.body %></h3>

      <h2 class="text-xl font-semibold mb-2">作成日</h2>
      <h1 class="text-md font-semibold mb-4"><%= @comment.created_at.strftime('%Y年%m月%d日 %H時%M分') %></h1>

  
      <div class="flex space-x-2">
        <%= link_to '編集', edit_admin_comment_path(@comment), class: 'text-green-500 hover:underline' %>
        <%= link_to '削除', admin_comment_path(@comment),
                    class: 'text-red-500 hover:underline',
                    data: { turbo_method: :delete, turbo_confirm: "コメントを削除しますか？" } %>
      </div>
    </div>
  </div>