config/routes.rb
Rails.application.routes.draw do

  root 'tops#top' # topページ

  resources :tops do
    collection do
      get :kiyac
      get :policy
      get :guide
    end
  end

  get 'login' => 'user_sessions#new', :as => :login # gem sorceryより。
  post 'login' => 'user_sessions#create' # gem sorceryのより。
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users, only: %i(new create show) do
    collection do
      get :usercat
    end
  end
  resource :profile, only: %i(show edit update destroy) do
    collection do
      get :delete_confirmation
    end
  end
  resources :cat_breeds, only: %i(index)
  resources :cats, only: %i(index new create update destroy)
  resources :password_resets, only: %i[new create edit update] # パスワードリセット用

  resources :posts, only: %i(index new show edit create update destroy) do
    resources :comments, only: %i[create update destroy], shallow: true
  end
  resources :likes, only: %i(create destroy)
  resources :post_by_cats, only: %i(index)
  resources :samebreedcats, only: %i(index)
  resources :like_lists, only: %i(index)
  resources :autocompletes, only: %i(index)

  resources :maps, only: %i(index show) do # GoogleマップAPIの導入により追加
    collection do
      get :search
    end
  end

  get 'line_events/show', to: 'line_events#show'
  post '/line_events', to: 'line_events#receive'
  put '/line_events', to: 'line_events#update'

  namespace :admin do
    root to: 'users#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i(index show edit update destroy)
    resources :posts, only: %i(index show edit update destroy)
    resources :cats, only: %i(index show edit update destroy)
    resources :tags, only: %i(index show edit update destroy)
    resources :comments, only: %i(index show edit update destroy)
  end
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :user
  belongs_to :cat_breed
  has_many :posts, dependent: :destroy
  mount_uploader :avatar, CatAvatarUploader # AvatarUploader アバターアップローダー、useで使ってるものと同じものを使う。
  enum gender: { Male: 0, Female: 1 }
  validates :name, presence: true, length: { maximum: 15 }
  validates :gender, presence: true
  validates :self_introduction, length: { maximum: 200 }

  # プロフィール画像解除用として追加。
  attr_accessor :remove_cat_avatar
  before_save :remove_cat_avatar_if_needed

  def self.ransackable_attributes(auth_object = nil)
    %w[name]  # 検索時に猫の名前を検索できる
  end

  def self.ransackable_associations(auth_object = nil)
    %w[health_records]
  end

  private

  # プロフィール画像解除用として追加。
  def remove_cat_avatar_if_needed
    self.avatar = nil if remove_cat_avatar == '1'
  end
end

app/controllers/admin/cats_controller.rb
class Admin::CatsController < Admin::BaseController
  def index
    @q = Cat.ransack(params[:q])
    @cats = @q.result(distinct: true).order(created_at: :desc)
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update(cat_params)
      flash[:success] = t('admin.messages.update')
      redirect_to admin_cats_path
    else
      flash.now[:danger] = t('admin.messages.update_faild')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy!
    flash[:success] = t('admin.messages.delete')
    redirect_to admin_cats_path
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :birthday, :self_introduction, :gender, :avatar, :avatar_cache, :cat_breed_id, :user_id, :remove_cat_avatar)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = current_user.cats.includes(:user).order(created_at: :asc)
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cat_params)
    if cat_params[:avatar].present?
      result = Vision.image_analysis(cat_params[:avatar])
      if result
        create_has_image # 添付画像が猫の画像だった場合の処理
      else
        create_bad_image # 添付画像が猫の画像以外の場合の処理
      end
    else
      create_not_image # 画像を添付していない場合の処理
    end
  end

  def update
    return unless set_cat.user_id == current_user.id

    if cat_params[:avatar].present?
      result = Vision.image_analysis(cat_params[:avatar])
      if result
        update_has_image # 添付画像が猫の画像だった場合の処理
      else
        update_bad_image # 添付画像が猫の画像以外の場合の処理
      end
    else
      update_not_image # 画像を添付していない場合の処理
    end
  end

  def destroy
    return unless set_cat.user_id == current_user.id

    @cat = Cat.find_by(id: params[:id])
    @cat.destroy!
    flash[:success] = t('messages.cats.delete')
    redirect_to cats_path, status: :see_other # 削除処理の時、「status: :see_other」をつけないと上手く機能しない。
  end

  private

  def set_cat
    @cat = current_user.cats.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(:name, :birthday, :self_introduction, :gender,
                                :avatar, :avatar_cache, :cat_breed_id, :remove_cat_avatar).merge(user_id: current_user.id)
  end

  # 新規猫プロフィール作成時、猫の画像を添付していた場合の処理
  def create_has_image
    if @cat.save
      flash[:success] = t('messages.cats.create')
      redirect_to cats_path
    else
      flash.now[:danger] = t('messages.cats.create_faild')
      render :new, status: :unprocessable_entity # renderでフラッシュメッセージを表示するときはstatus: :unprocessable_entityをつけないと動作しない。
    end
  end

  # 新規猫プロフィール作成時、猫以外の画像を添付していた場合の処理
  def create_bad_image
    @cat.avatar = nil # renderで戻る前に画像をnillにする処理
    flash.now[:danger] = t('messages.cats.cat_validation')
    render :new, status: :unprocessable_entity
  end

  # 新規猫プロフィール作成時、画像を添付していない場合の処理
  def create_not_image
    # 画像を添付していない場合の処理
    if @cat.save
      flash[:success] = t('messages.cats.create')
      redirect_to cats_path
    else
      flash.now[:danger] = t('messages.cats.create_faild')
      render :new, status: :unprocessable_entity # renderでフラッシュメッセージを表示するときはstatus: :unprocessable_entityをつけないと動作しない。
    end
  end

  # 猫プロフィール更新時、猫の画像を添付していた場合の処理
  def update_has_image
    @cat = Cat.find_by(id: params[:id])
    return if @cat.update(cat_params)

    flash.now[:danger] = t('messages.cats.update_faild')
    render turbo_stream: turbo_stream.replace(
      "flash-messages-container-edit-#{@cat.id}",
      partial: 'shared/flash_message',
      locals: { message: t('messages.cats.update_faild'), css_class: 'danger' }
    )
  end

  # 猫プロフィール更新時、猫以外の画像を添付していた場合の処理
  def update_bad_image
    # 添付ファイルが猫とは関係ない画像だった場合
    flash.now[:danger] = t('messages.cats.cat_validation')
    render turbo_stream: turbo_stream.replace(
      "flash-messages-container-edit-#{@cat.id}",
      partial: 'shared/flash_message',
      locals: { message: t('messages.cats.cat_validation'), css_class: 'danger' }
    )
  end

  # 猫プロフィール更新時、画像を添付していなかった場合の処理
  def update_not_image
    # 画像を添付していない場合の処理
    @cat = Cat.find_by(id: params[:id])
    return if @cat.update(cat_params)

    flash.now[:danger] = t('messages.cats.update_faild')
    # エラー時の Turbo Stream
    render turbo_stream: turbo_stream.replace(
      "flash-messages-container-edit-#{@cat.id}",
      partial: 'shared/flash_message',
      locals: { message: t('messages.cats.update_faild'),
                css_class: 'danger' }
    ), status: :unprocessable_entity
  end
end

app/views/admin/cats/_cat.html.erb
<div class="bg-white rounded-md shadow-md p-6 mb-6">
    <h1 class="text-xl font-semibold mb-2">・猫の名前</h1>
    <h3 class="text-lg font-semibold mb-4"><%= cat.decorate.cat_name %></h3>

    <h1 class="text-xl font-semibold mb-2">・飼い主さんのお名前</h1>
    <h4 class="text-lg font-semibold mb-4"><%= cat.user.name %></h4>

    <h3 class="text-xl font-semibold mb-2"><%= cat.decorate.cat_name %>の紹介</h3>
    <h4 class="text-lg mb-4"><%= cat.self_introduction %></h4>

    <!-- ボタン類 -->
    <div class="flex space-x-2">
      <%= link_to '詳細', admin_cat_path(cat), class: 'text-blue-500 hover:underline', id: "admin-cat-show-id-#{cat.id}" %>
      <%= link_to '編集', edit_admin_cat_path(cat), class: 'text-green-500 hover:underline', id: "admin-cat-edit-id-#{cat.id}" %>
      <%= link_to '削除', admin_cat_path(cat),
                  class: 'text-red-500 hover:underline',
                  data: { turbo_method: :delete, turbo_confirm: "#{cat.decorate.cat_name}の情報を削除しますか？" }, id: "admin-cat-delete-id-#{cat.id}" %>
    </div>
  </div>    

app/views/admin/cats/_search.html.erb
<%= search_form_for @q, url: url do |f| %>
  <%= f.search_field :name_cont, class: 'form-control text-black px-1', placeholder: '猫検索' %>
  <%= f.submit '検索', class: 'btn btn-primary' %>
<% end %>

app/views/admin/cats/edit.html.erb
<div class="container mx-auto mt-8 text-black">
  <h1 class="text-3xl font-semibold mb-6 text-white"><%= @cat.decorate.cat_name %>の編集ページ</h1>

  <div class="bg-white rounded-md shadow-md p-6 mb-6">
    <%= form_with model: @cat, url: admin_cat_path(@cat), local: true, html: { class: 'mb-4' } do |f| %>
      <div class="mb-4">
        <%= f.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.text_field :name, class: "form-input mt-1 block w-full border border-gray-300 rounded-md p-2" %>
      </div>

      <div class="mb-4">
        <%= f.label :user_id, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.collection_select :user_id, User.order(:name), :id, :name, { prompt: "飼い主を選択してください" }, { class: "form-input mt-1 block w-full border border-gray-300 rounded-md p-2" } %>
      </div>

      <!-- 他のフォームフィールドもここに追加 -->

      <div class="mb-4">
        <%= f.label :birthday, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.date_field :birthday, class: "form-input mt-1 block border border-gray-300 rounded-md p-2" %>
      </div>

      <div class="mb-4">
        <%= f.label :self_introduction, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.text_area :self_introduction, class: "form-input w-full h-32 p-2 border rounded-md focus:outline-none focus:shadow-outline" %>
      </div>

      <div class="mb-4">
        <%= f.label :gender, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.select :gender, Cat.genders.keys.map{|k| [I18n.t("enums.cat.gender.#{k}"), k]}, { prompt: "性別を選択してください" }, { class: 'appearance-none border rounded py-2 px-3 leading-tight focus:outline-none focus:shadow-outline bg-white' } %>
      </div>

      <div class="mb-4">
        <%= f.label :cat_breed_id, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.collection_select :cat_breed_id, CatBreed.order(:name), :id, :name, { prompt: "猫の種類を選択してください" }, { class: "form-input" } %>
      </div>

      <div class="mb-3">
        <%= f.label :avatar, for: 'avatar-file', class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.file_field :avatar, id: 'avatar-file', class: "form-control", accept: 'image/*', onchange: "previewImage(this);" %>
        <%= f.hidden_field :avatar_cache %>
      </div>

      <div class="mb-3">
        <%= image_tag @cat.avatar_url, id: 'preview', size: '300x200', class: 'mb-4' %>
      </div>

      <div class="mb-4">
        <%= f.check_box :remove_cat_avatar %>
        <%= f.label :remove_cat_avatar, "画像の設定を解除する" %>
      </div>

      <div class="mb-4">
        <%= f.submit "猫を更新する", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/cats/index.html.erb
<div class="container mx-auto mt-8 text-black">
    <h1 class="text-3xl font-semibold mb-6 text-white p-2">猫一覧</h1>

<div class="mb-4 p-4">
<%= render 'search', q: @q, url: admin_cats_path %>
</div>

<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
<%= render @cats %>
</div>

</div>

app/views/admin/cats/show.html.erb
<div class="container mx-auto mt-8 text-black">
  <h1 class="text-3xl font-semibold mb-6 text-white"><%= @cat.decorate.cat_name %>の詳細画面</h1>

  <div class="bg-white rounded-md shadow-md p-6 mb-6">
    <h1 class="text-xl font-semibold mb-2">・飼い主さんのお名前</h1>
    <h1 class="text-lg mb-4"><%= @cat.user.name %></h1>

    <h1 class="text-xl font-semibold mb-2">・猫ちゃんの猫種</h1>
    <h1 class="text-lg mb-4"><%= @cat.cat_breed.name %></h1>

    <% if @cat.birthday.present? %>
      <h1 class="text-xl font-semibold mb-2">この猫ちゃんの誕生日</h1>
      <h1 class="text-lg mb-4"><%= @cat.birthday.strftime('%Y年%m月%d日') %>だよ</h1>

      <h1 class="text-xl font-semibold mb-2">この猫ちゃんの年齢</h1>
      <h1 class="text-lg mb-4"><%= @cat.decorate.cat_age %></h1>
    <% end %>

    <h1 class="text-xl font-semibold mb-2">・この猫ちゃんの紹介</h1>
    <h1 class="text-lg mb-4"><%= @cat.self_introduction %></h1>

    <h1 class="text-xl font-semibold mb-2">・この猫ちゃんの性別</h1>
    <h1 class="text-lg mb-4"><%= @cat.gender_i18n %></h1>

    <h1 class="text-xl font-semibold mb-2">登録日</h1>
    <h1 class="text-lg mb-4"><%= @cat.created_at.strftime('%Y年%m月%d日 %H時%M分') %></h1>

    <div class="mb-4">
      <h1 class="text-xl font-semibold mb-2">・この猫ちゃんの写真</h1>
      <%= image_tag @cat.avatar_url, id: 'avatar-preview', class: 'w-full rounded-md shadow-md mb-4' %>
    </div>

    <!-- ボタン類 -->
    <div class="flex space-x-2">
      <%= link_to '編集', edit_admin_cat_path(@cat), class: 'text-blue-500 hover:underline' %>
      <%= link_to '削除', admin_cat_path(@cat),
                  class: 'text-red-500 hover:underline',
                  data: { turbo_method: :delete, turbo_confirm: "#{@cat.decorate.cat_name}の情報を削除しますか？" } %>
    </div>
  </div>
</div>