config/routes.rb
Rails.application.routes.draw do

  root 'tops#top' # topページ

  resources :tops do
    collection do
      get :kiyac
      get :policy
      get :guide
    end
  end

  get 'login' => 'user_sessions#new', :as => :login # gem sorceryより。
  post 'login' => 'user_sessions#create' # gem sorceryのより。
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users, only: %i(new create show) do
    collection do
      get :usercat
    end
  end
  resource :profile, only: %i(show edit update destroy) do
    collection do
      get :delete_confirmation
    end
  end
  resources :cat_breeds, only: %i(index)
  resources :cats, only: %i(index new create update destroy)
  resources :password_resets, only: %i[new create edit update] # パスワードリセット用

  resources :posts, only: %i(index new show edit create update destroy) do
    resources :comments, only: %i[create update destroy], shallow: true
  end
  resources :likes, only: %i(create destroy)
  resources :post_by_cats, only: %i(index)
  resources :samebreedcats, only: %i(index)
  resources :like_lists, only: %i(index)
  resources :autocompletes, only: %i(index)

  resources :maps, only: %i(index show) do # GoogleマップAPIの導入により追加
    collection do
      get :search
    end
  end

  get 'line_events/show', to: 'line_events#show'
  post '/line_events', to: 'line_events#receive'
  put '/line_events', to: 'line_events#update'

  namespace :admin do
    root to: 'users#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i(index show edit update destroy)
    resources :posts, only: %i(index show edit update destroy)
    resources :cats, only: %i(index show edit update destroy)
    resources :tags, only: %i(index show edit update destroy)
    resources :comments, only: %i(index show edit update destroy)
  end
end

app/views/shared/_before_login_header.html.erb
<div class = "text-black flex">
  <%= link_to root_path, class:'p-1' do %>
    <%= image_tag 'logo.webp', size: "100x100"  %>
  <%end%>
  <div class="drawer-end flex items-center">
    <input id="drawer" type="checkbox" class="drawer-toggle" />
    <label for="drawer" class="drawer-button right-0 m-4 absolute">
      <i id="bars" class="fa-solid fa-bars fa-2x"></i>
    </label>
    <div class="drawer-side z-10">
      <label for="drawer" class="drawer-overlay"></label>
      <ul class="menu p-4 w-60 md:w-80 h-full accent-color text-base-content text-black">
        <div class="mt-8">
          <div class="mb-8"><%= link_to '投稿一覧', posts_path, class: 'whitespace-nowrap text-lg md:text-xl lg:text-2xl hover:text-white' %></div>
          <div class="mb-8"><%= link_to 'Sign Up',new_user_path, class: 'whitespace-nowrap text-lg md:text-xl lg:text-2xl hover:text-white' %></div>
          <div class="mb-8"><%= link_to 'Login',login_path, class: 'whitespace-nowrap text-lg md:text-xl lg:text-2xl hover:text-white' %></div>
        </div>
        <div class="mt-8"><%= link_to 'How to Use',guide_tops_path, class: 'whitespace-nowrap text-lg md:text-xl lg:text-2xl hover:text-white' %></div>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
    <ul>
      <% object.errors.each do |error| %>
        <li>・<%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %> px-4 py-2">
    <%= value %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="p-4 text-black">
  <div class="text-sm md:text-base flex justify-center space-x-10">
    <%= link_to '利用規約', kiyac_tops_path, class:'text-center' %>
    <%= link_to 'プライバシーポリシー', policy_tops_path, class:'text-center' %>
    <%= link_to '運営元', 'https://twitter.com/tkm9353', class:'text-center' %>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="text-black flex">
  <%= link_to posts_path, class:'p-1' do %>
    <%= image_tag 'logo.webp', size: "100x100"  %>
  <%end%>
  <div class="drawer-end flex items-center">
    <input id="drawer" type="checkbox" class="drawer-toggle" />
    <label for="drawer" class="drawer-button right-0 m-4 absolute">
      <i id="bars" class="fa-solid fa-bars fa-2x"></i>
    </label>
  <div class="drawer-side z-10">
    <label for="drawer" class="drawer-overlay"></label>
    <ul class="menu p-4 w-60 md:w-80 h-full accent-color text-base-content text-black">
      <div class="mt-8">
        <div class="mb-8"><%= link_to '投稿一覧', posts_path, class: 'whitespace-nowrap text-lg md:text-xl lg:text-2xl hover:text-white' %></div>
        <div class="mb-8"><%= link_to '動物病院検索', search_maps_path, class: 'whitespace-nowrap text-lg md:text-xl lg:text-2xl hover:text-white' %></div>
        <div class="mb-8"><%= link_to 'マイ猫\'s', cats_path, class: 'whitespace-nowrap text-lg md:text-xl lg:text-2xl hover:text-white' %></div>
        <div class="mb-8"><%= link_to "#{current_user.name}さん",profile_path, class: 'whitespace-nowrap text-lg md:text-xl lg:text-2xl hover:text-white' %></div>
        <div class="mb-8"><%= link_to 'Logout', logout_path, data: { turbo_method: :delete, turbo_confirm: 'ログアウトしますか？' }, class: 'whitespace-nowrap text-lg md:text-xl lg:text-2xl hover:text-white' %></div>
      </div>
      <div class="mt-8"><%= link_to 'How to Use',guide_tops_path, class: 'whitespace-nowrap text-lg md:text-xl lg:text-2xl hover:text-white' %></div>
    </ul>
  </div>
  </div>
</div>