config/routes.rb
Rails.application.routes.draw do

  root 'tops#top' # topページ

  resources :tops do
    collection do
      get :kiyac
      get :policy
      get :guide
    end
  end

  get 'login' => 'user_sessions#new', :as => :login # gem sorceryより。
  post 'login' => 'user_sessions#create' # gem sorceryのより。
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  resources :users, only: %i(new create show) do
    collection do
      get :usercat
    end
  end
  resource :profile, only: %i(show edit update destroy) do
    collection do
      get :delete_confirmation
    end
  end
  resources :cat_breeds, only: %i(index)
  resources :cats, only: %i(index new create update destroy)
  resources :password_resets, only: %i[new create edit update] # パスワードリセット用

  resources :posts, only: %i(index new show edit create update destroy) do
    resources :comments, only: %i[create update destroy], shallow: true
  end
  resources :likes, only: %i(create destroy)
  resources :post_by_cats, only: %i(index)
  resources :samebreedcats, only: %i(index)
  resources :like_lists, only: %i(index)
  resources :autocompletes, only: %i(index)

  resources :maps, only: %i(index show) do # GoogleマップAPIの導入により追加
    collection do
      get :search
    end
  end

  get 'line_events/show', to: 'line_events#show'
  post '/line_events', to: 'line_events#receive'
  put '/line_events', to: 'line_events#update'

  namespace :admin do
    root to: 'users#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i(index show edit update destroy)
    resources :posts, only: %i(index show edit update destroy)
    resources :cats, only: %i(index show edit update destroy)
    resources :tags, only: %i(index show edit update destroy)
    resources :comments, only: %i(index show edit update destroy)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags, dependent: :destroy

  validates :name, uniqueness: true # タグの重複を避ける

  def self.ransackable_attributes(auth_object = nil)
    %w[name]  # 検索時にtagの名前を検索できる
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::BaseController
  def index
    @q = Tag.ransack(params[:q])
    @tags = @q.result(distinct: true).order(created_at: :desc)
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    return tags_nil_check if tag_params[:name] == ''

    if @tag.update(tag_params)
      flash[:success] = t('admin.messages.update')
      redirect_to admin_tag_path(@tag)
    else
      flash.now[:danger] = t('admin.messages.update_faild')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy!
    flash[:success] = t('admin.messages.delete')
    redirect_to admin_tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

  # タグの数チェック
  def tags_nil_check
    flash.now[:danger] = t('admin.messages.update_faild')
    render :edit, status: :unprocessable_entity
  end
end

app/views/admin/tags/_search.html.erb
<%= search_form_for @q, url: url do |f| %>
  <%= f.search_field :name_cont, class: 'form-control text-black px-1', placeholder: 'タグ検索' %>
  <%= f.submit '検索', class: 'btn btn-primary' %>
<% end %>

app/views/admin/tags/_tag.html.erb
<div class="bg-white rounded-md shadow-md p-6 mb-6">
    <h1 class="text-xl font-semibold mb-2">
      <%= link_to tag.name, admin_tag_path(tag), class: "text-blue-500 hover:underline" %>
    </h1>
    <h3 class="text-gray-600 mb-2">タグ作成日</h3>
    <h3 class="text-sm mb-4 text-black"><%= tag.created_at.strftime('%Y年%m月%d日 %H時%M分') %></h3>
  
    <div class="flex">
      <%= link_to '詳細', admin_tag_path(tag), class: "text-blue-500 hover:underline mr-4", id: "admin-tag-show-id-#{tag.id}" %>
      <%= link_to '編集', edit_admin_tag_path(tag), class: 'text-green-500 hover:underline mr-4', id: "admin-tag-edit-id-#{tag.id}" %>
      <%= link_to '削除', admin_tag_path(tag), data: { turbo_method: :delete, turbo_confirm: "タグを削除しますか？" }, class: "text-red-500 hover:underline", id: "admin-tag-delete-id-#{tag.id}" %>
    </div>
  </div>

app/views/admin/tags/edit.html.erb
<div class="container mx-auto mt-8">
  <h1 class="text-3xl font-semibold mb-6">タグ編集</h1>

  <div class="bg-white rounded-md shadow-md p-6 mb-6">
    <%= form_with(model: @tag, url: admin_tag_path(@tag), local: true, html: { class: 'mb-4' }) do |f| %>
      <div class="mb-4">
        <%= f.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.text_field :name, class: "form-input text-black mt-1 block w-full border border-gray-300 rounded-md p-2" %>
      </div>

      <div class="mb-4">
        <%= f.submit "更新", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container mx-auto mt-8">
  <h1 class="text-3xl font-semibold mb-6 p-2">タグ一覧</h1>
  
  <div class="mb-4 p-4">
    <%= render 'search', q: @q, url: admin_tags_path %>
  </div>

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
    <%= render @tags %>
  </div>
  </div>

app/views/admin/tags/show.html.erb
<div class="container mx-auto mt-8">
  <h1 class="text-3xl font-semibold mb-6">タグ詳細</h1>

  <div class="bg-white rounded-md shadow-md p-6 mb-6">
    <h1 class="text-xl font-semibold mb-2 text-black">
      <%= @tag.name %>
    </h1>
    <h3 class="text-black mb-2">作成日時</h3>
    <h3 class="text-sm mb-4 text-black"><%= @tag.created_at.strftime('%Y年%m月%d日 %H時%M分') %></h3>

    <div class="flex mb-4">
      <%= link_to '編集', edit_admin_tag_path(@tag), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mr-4" %>
      <%= link_to '削除', admin_tag_path(@tag), data: { turbo_method: :delete, turbo_confirm: "タグを削除しますか？" }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mr-4" %>
    
    </div>

    <% @tag.posts.each do |post| %>
      <div class="mb-2">
        <h1 class="text-lg font-semibold text-black">・タグに紐づいている投稿タイトル名</h1>
        <%= link_to post.title, admin_post_path(post), class: "text-blue-500 hover:underline" %>
      </div>
    <% end %>
  </div>
</div>